name: create-branch
on: create
jobs:
  create-workspace:
    if: ${{ contains(github.ref, 'refs/heads/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Init
        working-directory: terraform
        run: |
          mkdir -p ~/.config/gcloud
          echo '${{ secrets.GCLOUD_CREDENTIALS }}' > ~/.config/gcloud/application_default_credentials.json
          terraform init

      - name: Create Workspace
        working-directory: terraform
        run: |
          BRANCH=`echo "$GITHUB_REF" | cut -d/ -f3- | tr / -`
          terraform workspace new $BRANCH
